### ISSUE TITLE
misc optimizations

### ISSUE THREAD

**Issue by goozang-records** [4meta5/huffman-codec#2]
will address when I feel like it, code is already clean now
- [ ] remove CharDNEinDict and make char conversion infallible, use 1i32 
- [ ] use hashbrown::HashMap instead of BTreeMap
- [ ] look into using lifetimes instead of Rc<Tree>
- [ ] map -> heap -> tree can definitely be improved to remove like 2-3 allocations per element per step

**Comment by ghost** [comment]
You could use an array of `Option<u8>` for all ascii characters and then for any others use a `HashMap`

**Comment by ghost** [comment]
lifetimes with a tree would probably be impossible however you could have the root node store a vector of each node and then instead of `Rc` use a index into the roots vector

**Comment by goozang-records** [comment]
> lifetimes with a tree would probably be impossible however you could have the root node store a vector of each node and then instead of `Rc` use a index into the roots vector

Interesting, I'd like to see this and compare benchmark results.
